Feature/ot207 19
alkemyTech/OT207-server pull request #10
Opened 2022-05-23 23:29 UTC by Martinpozzoli

Buenas, la entidad News esta relacionada con Category no sabia si esperar a que esa entidad este terminada o seguir, cualquier cosa que haya que corregir lo cambio

2022-05-24 03:48 UTC, turcoamado requested changes
Te marque dos detalles, uno en la entidad y otro en el repository

2022-05-24 03:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/News.java
> +    @Column(name = "name", length = 40, nullable = false)
El _nullable = false_ que utilizas en todos los NOT NULL no esta mal, pero es redundante, ya que le estas poniendo tambien la annotation @NotNull

2022-05-24 03:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/News.java
> +    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
Esta relacion deberia ser @ManyToOne, porque una noticia puede pertenecer a mas de una categoria (podes pensarla al reves si queres, una categoria puede tener muchas noticias). Habr[ia que definir a su vez el @JoinColumn

2022-05-24 03:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/INewsRepository.java
> +public interface INewsRepository extends JpaRepository<News, Long> {
En este caso podemos obviar la I delante del nombre de la clase, ya que no vamos a crear nunca la implementacion.
Y te esta faltando la annotation @Repository

2022-05-24 20:19 UTC, Martinpozzoli commented
Ya arregle lo que faltaba, tuve problemas para mergear localmente pero creo que esta todo en orden

2022-05-25 00:11 UTC, turcoamado approved these changes
Buenisimo!

2022-05-25 15:16 UTC, Martinpozzoli commented
Me di cuenta de que no había agregado el @JoinColumn sobre categoryId, lo acabo de hacer y pushee la rama de nuevo, que tendría que hacer ahora? perdón por el lio no estaba acostumbrado a git

2022-05-25 15:39 UTC, turcoamado commented
> Me di cuenta de que no había agregado el @joincolumn sobre categoryId, lo acabo de hacer y pushee la rama de nuevo, que tendría que hacer ahora? perdón por el lio no estaba acostumbrado a git

No pasa nada Martin! Como aun no mergeaste, al hacer el commit y push se actualiza el PR automaticamente, fijate que ya lo tenes en este codigo a lo que pusiste hace un ratito. Podes mergear tranqui que no rompiste nada.
No pidas perdon, estamos para aprender

2022-05-26 18:32 UTC, merged