Feature/ot207 24
alkemyTech/OT207-server pull request #19
Opened 2022-05-27 00:10 UTC by Martinpozzoli

Le hice unos cambios a unas entidades porque me largaba errores al crear las tablas, al hacer referencia a otras entidades salian por ejemplo como:
@ManyToOne()
@JoinColumn ....
private Long newsId;

Las deje de esta forma:
@ManyToOne()
@JoinColumn ....
private News newsId;

No estoy seguro de si me corresponde hacerlo pero sino me salian errores.

Asi es como van quedando en la base de datos:
![Untitled](https://user-images.githubusercontent.com/63267347/170603445-3862f73f-e888-4382-bcef-b872b3042724.png)

2022-05-27 03:53 UTC, turcoamado commented
> Le hice unos cambios a unas entidades porque me largaba errores al crear las tablas, al hacer referencia a otras entidades salian por ejemplo como: @manytoone() @joincolumn .... private Long newsId;
> 
> Las deje de esta forma: @manytoone() @joincolumn .... private News newsId;
> 
> No estoy seguro de si me corresponde hacerlo pero sino me salian errores.
> 
> Asi es como van quedando en la base de datos: ![Untitled](https://user-images.githubusercontent.com/63267347/170603445-3862f73f-e888-4382-bcef-b872b3042724.png)

Si! De hecho esta perfecto lo que planteas, se me paso a mi en la revision. Un objeto que se realaciona con otro en el codigo se relaciona mediante objeto, en la DB mediante el id, por eso usamos el joinColumn

2022-05-27 03:55 UTC, turcoamado requested changes

2022-05-27 03:55 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/controller/AuthController.java
> +    private UserRepository userRepository;
No deberias inyectar el repository en el controller, te estas salteando una capa. Primero hay que ir al service y alli se debe llamar al repository. Fijate que lo estas haciendo bien cuando llamas al metodo **register()**

2022-05-27 03:55 UTC, turcoamado commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost/ong207?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
Ojo que estas subiendo el archivo properties!

2022-05-27 03:55 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/service/impl/UserServiceImpl.java
> +        userDto.setRoleId(roleRepository.getById(1L));
Esto no me convence mucho, primero porque se le esta pasando de forma hardcoded un valor y ese valor es un id. Ese id esta haciendo referencia a un rol, a cual? Tiene sentido que siempre que se registra un usuario lo haga con el rol USER y no el ADMIN, pero la forma correcta no seria pasandole un id (mas alla de que lo sepamos), sino que deberiamos asignar el objeto directamente. Quizas el error esta tambien en que estamos guardando un id, deberiamos guardar el rol como objeto (se me paso a mi en la revision incial)
Dicho esto, cuando se setea el rol deberia setearse el objeto completo, y de alguna manera obtener USER

2022-05-27 03:55 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/controller/AuthController.java
> +        if(userRepository.existsByEmail(userDto.getEmail())){
Me gusta la validacion! Lo que le agregaria ya seria el tema del manejo de los mensajes

2022-05-27 20:38 UTC, Martinpozzoli commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost/ong207?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
uhhh se me re paso

2022-05-27 20:38 UTC, Martinpozzoli commented on src/main/java/com/alkemy/ong/auth/controller/AuthController.java
> +    private UserRepository userRepository;
Bien eso lo estoy solucionando

2022-05-27 20:41 UTC, Martinpozzoli commented on src/main/java/com/alkemy/ong/auth/controller/AuthController.java
> +    private UserRepository userRepository;
Bien eso lo estoy solucionando

2022-05-27 20:42 UTC, Martinpozzoli commented on src/main/java/com/alkemy/ong/auth/service/impl/UserServiceImpl.java
> +        userDto.setRoleId(roleRepository.getById(1L));
Ya modifique eso para asignar el rol como un objeto y lo esta asignando de esa forma, me quedaron dudas de si un user puede tener uno o mas roles, por ejemplo ser USER y colaborador en un futuro por ejemplo o si nos limitamos a USER y ADMIN

2022-05-28 17:10 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/service/impl/UserServiceImpl.java
> +        userDto.setRoleId(roleRepository.getById(1L));
Para nuestro proyecto nos quedemos unicamente con esos dos tipos, y pensemos que si tiene uno no puede tener el otro. Para no complicarnos la vida

2022-05-28 17:14 UTC, turcoamado approved these changes
Bueno ahora si! Mucho mejor! Lo unico que cambiaria seria la implementacion de los mensajes de error para que no esten de forma hardcoded, pero si queres podes mergear esto y cuando trabajen sobre ese tema lo modifican

2022-05-28 20:21 UTC, Martinpozzoli commented
Se hizo re largo pero solucione lo que faltaba y mejore parte del manejo de errores y mensajes con la ayuda del grupo, sigue hardcodeado pero ya charlamos sobre como mejorarlo.
Ahí va un ejemplo de la petición funcionando con un registro correcto:
![funciona](https://user-images.githubusercontent.com/63267347/170841565-d39c6560-06e6-4c57-a507-3a214d245cfb.png)
Cuando se carga un usuario con correo repetido:
![email conflict](https://user-images.githubusercontent.com/63267347/170841608-a2d1a317-a1dd-43f3-8a8f-dc12f89ef9d5.png)
Cuando no se carga uno de los valores:
![validation bad-request](https://user-images.githubusercontent.com/63267347/170841652-71bb69e9-830d-4f3c-af77-bcef7230906d.png)

2022-05-28 20:21 UTC, merged