Feature/ot207 42 endpoint categories
alkemyTech/OT207-server pull request #21
Opened 2022-05-27 20:21 UTC by MacaHannaArenas

COMO usuario administrador
QUIERO agregar una categoría nueva al sistema
PARA categorizar las Novedades

Criterios de aceptación:
POST /categories - Deberá validar que se envíe el campo name, y el mismo sea un string

2022-05-28 17:08 UTC, turcoamado requested changes

2022-05-28 17:08 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +    @Pattern(regexp = "[a-zA-Z\\s]*", message = "Name cannot contain numbers or characters other than letters")
Buenisimo esto Maca!

2022-05-28 17:08 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +    CategoryMapper categoryMapper;
A este y al siguiente ponele el private por delante

2022-05-28 17:08 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +            throw new NotFoundException(e.getMessage());
Esta bien que hayas puesto todo dentro de un try catch, pero no es correcta la exception. Para que te arroje un NotFoundException tenes que buscar algo que no se encontro y aca en ninguna de tus operaciones estas buscando algo, primero convertis a entidad lo lo que te viene por parametro como DTO, luego lo persistis en DB y finalmente lo volves a convertir a DTO para enviarlo al controller.
Si explota en este caso seria por un problema del servidor, por lo tanto el error seria otro, simplemente usaria throw new Exception.
Por otro lado, aca deberiamos intentar utilizar el handler de excepciones que ya fue creado, y quizas se podria agregar alguna nueva que indique si la categoria que se intenta guardar ya existe, eso requeriria que primero se valide si el nombre ingresado ya esta en la DB, es decir hay que buscar por el nombre, comparar con lo que se ingresa, si es diferente persistir, si es igual lanzar una excepcion que indique que ya existe. Sino podriamos tener muchas categorias con el mismo nombre

2022-05-28 17:08 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +    public Category categoryDtoToCategoryEntity(CategoryDto categoryDto){
En ambos mappers unicamente estas seteando el name, que pasa con los demas cmapos? Ojo porque cuando lo utilices vas a perder informacion, por ejemplo, el dto tiene name, description e image, cuando conviertas a entity para persistir le seteas solo el name, si los demas datos no son null los estamos perdiendo.
Lo mismo al reves, si de la DB recuperamos todos los campos cuando vamos a devolverlo al controller solamente le estas pasando el name, porque en la conversion se setea eso nada mas

2022-05-28 19:16 UTC, MacaHannaArenas commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +            throw new NotFoundException(e.getMessage());
perfecto ahora veo esto entonces, gracias 
justo estamos ahora hablando con los chicos para ver si podemos crear una que sea AlreadyExistException

2022-05-28 19:17 UTC, MacaHannaArenas commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +    @Pattern(regexp = "[a-zA-Z\\s]*", message = "Name cannot contain numbers or characters other than letters")
gracias https://reflectoring.io/bean-validation-with-spring-boot/ aca saque mucha info sobre las validaciones de spring

2022-05-28 19:18 UTC, MacaHannaArenas commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +    public Category categoryDtoToCategoryEntity(CategoryDto categoryDto){
ahh bien, no los puse por que por ahora estaba metiendo solo lo que usaba en mi ticket, pero me fijo asi agrego los demas campos y que el dto este completo

2022-05-31 02:10 UTC, turcoamado approved these changes
Buenisimo Maca!

2022-05-31 23:39 UTC, MacaHannaArenas commented
En el ultimo commit se arreglo lo de registro usuarios 
![imagen](https://user-images.githubusercontent.com/92378693/171300902-6df6f8e4-bf67-4a72-aaae-5417471030cf.png)

2022-06-01 01:44 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
> +        return new User(user.getEmail(),user.getPassword(),user.isEnabled(),user.isAccountNonExpired(),user.isCredentialsNonExpired(),user.isAccountNonLocked(),roles);
Por que estan haciendo un new User? No se supone que ya encontraron el usuario logueado en la linea 48? Se deberia devolver ese mismo no una nueva instancia, fijate que lo estas creando con los mismos datos que te trajiste

**EDIT**
Perdon ya entendi, estas creando ahora un objeto del tipo User y no UserEntity. Esta bien, pero prueben que pasa si salis y te volves a loguear, ese usuario vive unicamente en la sesion verdad?

2022-06-01 01:51 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +        if (flag) {
Para que es este flag? Por lo que veo el mapper hasta ahora lo usan una sola vez y se lo pasas siempre en false, por lo que no va a entrar nunca.
Para simplificar, asuman que cada usuario puede tener un unico rol, total no vamos a hacer algo para agregarle o quitarle roles, se podria pensar, pero no esta en el backlog y es complicarla demasiado por ahora.

2022-06-01 01:56 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/UserEntity.java
> +    public UserEntity() {
Podrian haber evitado el constructor de esta entity utilizando las annotation de Lombok que vi que sacaron, lo mismo con el constructor vacio.
Ya que lo dejaron, aca pueden setearle la fecha de creacion y actualizacion. Luego cuando se realiza el update del user hay que modificar unicamente la fecha de actualizacion

2022-06-01 21:54 UTC, MacaHannaArenas commented
![imagen](https://user-images.githubusercontent.com/92378693/171508252-024cbf1c-cd1d-4f5d-90f7-3f815128d7eb.png)
LOGIN CORREGIDO FUNCIONANDO CON JWT

2022-06-01 22:29 UTC, merged