OT207-36
alkemyTech/OT207-server pull request #28
Opened 2022-06-03 00:02 UTC by NoviceYh

Le saque importaciones que no se estaban usando.
Agregue el metodo getUserInfo en UserDetailsCustomService
y la ruta /auth/me en el controlador.
Ahi en la imagen se ve que me devuelve los datos con el token, nose porque dice que tiene conflictos pero lo pusheo
 para que lo veas
![Captura de pantalla (25)](https://user-images.githubusercontent.com/94920495/171759501-350c17b3-e963-4e6b-a361-54d78a6bf65f.png)
,

2022-06-03 00:04 UTC, NoviceYh commented
En src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java recuerdo haber borrado un throws Exception que creo no hacia falta
 y en src/main/java/com/alkemy/ong/dto/CategoryDto.java borre muchas importaciones que no se usaban, nose si hice algun cambio mas

2022-06-05 00:41 UTC, turcoamado requested changes

2022-06-05 00:41 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/controller/AuthController.java
> +        String jwt = token.substring(7);
Esto no esta bien aca, vos tenes que obtener el token en el servicio, no le llega por parametro. Deberias recibir un HttpServletRequest y eso se lo envias al servicio, alli haces la obtencion del token. Entonces la firma de tu endpoint quedaria algo asi:
`public ResponseEntity<UserProfileDto> getProfile(HttpServletRequest request) {`
Y luego en el servicio obtenes el token de forma similar a lo que hiciste aca, asi:
```
String authorizationHeader = request.getHeader("Authorization");
jwt = authorizationHeader.substring(7);
```
Y con ese dato llamas a tu metodo extractUsername(jwt), pero lo haces todo dentro del service

2022-06-07 01:11 UTC, turcoamado approved these changes
Ahora si! Joya

2022-06-08 14:10 UTC, NoviceYh commented
Ya hice el nuevo PR, ya se podria cerrar este

2022-06-08 22:19 UTC, closed without merging