Feature/ot207 41
alkemyTech/OT207-server pull request #33
Opened 2022-06-05 17:06 UTC by Martinpozzoli

Buenas el criterio era "GET a /categories/:id . Mostrará todos los campos de una categoría en base al id enviado por parámetro. En el caso de que no exista, devolverá un error con un código de estado 404."
Paso capturas:
Funcionando:
![working](https://user-images.githubusercontent.com/63267347/172061832-871ce8b4-5178-4f5b-959f-7d4f16c2132c.png)
Cuando no se encuentra categoria con ese id:
![Error](https://user-images.githubusercontent.com/63267347/172061893-b4e6c6da-9625-4b97-bf5a-9a57463e1240.png)

2022-06-05 19:15 UTC, turcoamado requested changes
Dos cosas para comentarte, una es que te falto hacer que unicamente sea para el usuario con rol de administrador, tenes que agregar el permiso en el archivo de configuracion de jwt.
La otra es que en una de tus imagenes, cuando se muestra el detalle aparece el id en null, por que sucede esto? Hay algo mal ahi, nunca un id puede ser null

2022-06-05 19:15 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        Category categoryEntity = categoryRepository.findById(id).orElseThrow(() -> new NotFoundException("Category not found"));
Bien usada la expresion lambda aca!

2022-06-07 20:32 UTC, Martinpozzoli commented
Buenas, ya cambie lo del acceso para que solo pueda usarlo un admin. 
Lo del id que salia null tambien esta arreglado.
![id shows](https://user-images.githubusercontent.com/63267347/172476759-1e85e281-18e1-41cb-a224-d9a121ce7976.png)

2022-06-08 22:08 UTC, turcoamado approved these changes

2022-06-09 01:13 UTC, merged