Feature/ot207-40
alkemyTech/OT207-server pull request #40
Opened 2022-06-08 03:43 UTC by diego-sejas

COMO usuario administrador
QUIERO listar las Categorías
PARA poder gestionarlas

Criterios de aceptación:
GET a /categories. Devolverá el listado de categories. Solamente devolverá el campo name de las mismas

2022-06-08 03:56 UTC, diego-sejas commented
Realizo el Login con user ROLE_USER
![ROLE_USER](https://user-images.githubusercontent.com/54463198/172527311-fa10acd7-6950-48ca-bdfa-5922fc887370.png)
realizo la petición GET a http://localhost:8080/categories
![ROLE_USER](https://user-images.githubusercontent.com/54463198/172527579-d38b8d66-63a4-402f-873e-fde4c2e497d6.png)
hago Login con user ROLE_ADMIN
![ROLE_ADMIN](https://user-images.githubusercontent.com/54463198/172527978-40e4c797-596c-4e4e-a801-13ae6567bccf.png)
realizo la petición GET a http://localhost:8080/categories , que me devuelve la lista de categorias solo el name.
![GET ROLE_ADMIN](https://user-images.githubusercontent.com/54463198/172528148-8074a53d-c59a-490c-b6db-d410d2904f69.png)

2022-06-08 22:16 UTC, turcoamado requested changes
Ojo que incluiste el properties. 

Justo vi que ahi tenias los mensajes, se ve que ya habias implementado de alguna forma lo que yo les comente, la idea es la misma que realizaste en ese proyecto del cual sacaste el properties, solo que teniendo uno propio para los mensajes

2022-06-08 22:16 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        for (Category category : categories) {
Esto tambien lo podrias haber resuelto con una expresion lambda
`categories.forEach{ category -> responseDTos.add(categoryResponseDto(category)) }`

No esta mal lo que hiciste, solo te dejo el comentario para que lo sepas. Siempre esta bueno agregar programacion funcional cuando se pueda

2022-06-09 05:33 UTC, diego-sejas commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        for (Category category : categories) {
Si , no me percate del poperties. Dale perfecto tratare de implementar lo que me comentas sobre agregar programación funcional y lo de los mensajes quedo de otro proyecto.

2022-06-09 15:29 UTC, merged