feature/OT207-56 Endpoint Detalle Slides
alkemyTech/OT207-server pull request #52
Opened 2022-06-10 22:36 UTC by diego-sejas

COMO usuario administrador
QUIERO ver el detalle de Slides
PARA ver el contenido de forma más detallada.

Criterios de aceptación:

Se debe hacer una peticion GET a /Slides/:id . 

Mostrará todos los campos del slide en base al id enviado por parámetro. 

En el caso de que no exista, devolverá un error con un código de estado 404

Detalles
Responsable

Diego Sejas
Informador
Nicole Rappoport
Story Points

2
Code Quality

Ninguno
Code Performance v2

Ninguno
Buenas prácticas

Ninguno
Task Performance

Ninguno
Sprint

[OT207 Sprint 4](https://alkemy-labs.atlassian.net/secure/GHGoToBoard.jspa?sprintId=1593)
Epic Link

[Slides](https://alkemy-labs.atlassian.net/browse/OT207-11)
Prioridad

Medium
Clockify

Start / Stop
Más campos
Estimación original, Seguimiento de tiempo
Creado 17 de mayo de 2022, 19:56
Actualizado hace 3 horas
Configurar
Actividad
Mostrar:

Todo

Comentarios

Historial

Registro de trabajo

Más recientes primero

2022-06-10 22:41 UTC, diego-sejas commented
GET a Slides con id 2 .
![GET slides-id2](https://user-images.githubusercontent.com/54463198/173159351-9bf84261-7bf8-4c79-b1c6-797cf814d67c.png)

GET a Slides con id inexistente.
![GET slides-id inexistente](https://user-images.githubusercontent.com/54463198/173159472-2d1f10b6-f7a0-4455-9832-d84522f15468.png)

2022-06-11 19:24 UTC, turcoamado requested changes
Esta bien! Solo te falto cumplir con la parte del rol administrador

2022-06-11 19:24 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
> +        Slides slidesEntity = slidesRepository.findById(id).orElseThrow(() -> new NotFoundException("Slides with id provided not found"));
Me gusta como utilizaste la expresion lambda aca!

2022-06-11 19:32 UTC, diego-sejas commented on src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
> +        Slides slidesEntity = slidesRepository.findById(id).orElseThrow(() -> new NotFoundException("Slides with id provided not found"));
Si si , lo hice así por la sugerencia que me diste en el otro PR.

2022-06-11 23:59 UTC, diego-sejas commented
Perdón lo del ROL Administrador ,no lo inclui. Las peticiones de las imágenes anteriores fueron realizadas con usuario ROLE_ADMIN.
![image](https://user-images.githubusercontent.com/54463198/173202354-0e2b340c-d02e-475a-a443-5d8de2e95fd2.png)

USUARIO_ROLES
![image](https://user-images.githubusercontent.com/54463198/173202373-e7770e81-7850-429b-9921-c0af9fba174c.png)

LOGUIN con USER
![image](https://user-images.githubusercontent.com/54463198/173208698-07a0a00c-95dc-4805-ae4c-245811c75e63.png)

PETICION GET con ROL_USER
![image](https://user-images.githubusercontent.com/54463198/173208745-622445f2-2b49-4f8d-a18b-fe1bd5266fff.png)

2022-06-12 20:15 UTC, turcoamado approved these changes
Ah esta bien! Entonces debe estar en la config de jwt y no lo vi. Joya

2022-06-12 23:03 UTC, diego-sejas commented
Turco , tenes razón , no estaba SecurityConfiguration . La incluyo en la próxima PR.

2022-06-12 23:03 UTC, merged