feature/OT207-75
alkemyTech/OT207-server pull request #53
Opened 2022-06-11 14:48 UTC by AlanShalom

![MySQL listComments](https://user-images.githubusercontent.com/85803526/173192703-40f34918-c60a-4f02-b93a-1380a9efec56.jpg)
![Postman getCommentsListOrderByCDate](https://user-images.githubusercontent.com/85803526/173192711-d77a6369-bc58-4b44-8c7c-35416afa9403.jpg)

Cargue los comentarios en la base de datos manualmente ya que no hay todavía un método para crearlos

2022-06-11 19:31 UTC, turcoamado requested changes
El PR esta bien, te marque dos cosas, una es un mensaje para indicar que no hay elementos si la lista esta vacia, para que quede mas bonito a la hora de mostrarlo nada mas. Y la otra es un tema con los permisos, para que lo tengas en cuenta solamente, no hace falta que lo modifiques en este caso, ojo con los que si tienen parametros, esos hay que revisarlos

2022-06-11 19:31 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
> +                .antMatchers("/auth/users", "/auth/users/*", "/api/assets/upload", "/organization/public", "/categories/:id", "/activities", "/comments").hasAnyAuthority(RolName.ROLE_ADMIN.toString()
Ojo con como pusiste esto. Si estuviesemos utilizando un endpoint cualquiera donde la ruta sea /comments no podria ser accesible por otro usuario que no sea administrador, como este va a ser un list y no vamos a tener otra ruta hacia /comments parametros no esta mal, pero hay que tener cuidado, porque fijate el otro por ejemplo, el de categories/:id, ahi vos podes tener un get, update, delete, post, patch y estas obligando a que siempre sea mediante usuario administrador, puede que este bien pero puede que no, segun el analisis de los otros requerimientos

2022-06-11 19:31 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentaryServiceImpl.java
> +     return DtoList;
Yo le agregaria un mensaje si la lista esta vacia, para no devolver simplemente el body vacio. En este caso a fines de mostrar la api mediante postman o swagger, para que sea mas entendible nada mas

2022-06-12 17:22 UTC, AlanShalom commented on src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
> +                .antMatchers("/auth/users", "/auth/users/*", "/api/assets/upload", "/organization/public", "/categories/:id", "/activities", "/comments").hasAnyAuthority(RolName.ROLE_ADMIN.toString()
Genial, ahora me quedo claro. Gracias por la explicación. Ya arregle todos los que fui agregando yo al security.

2022-06-12 20:07 UTC, turcoamado approved these changes
Joya!

2022-06-12 23:10 UTC, merged