findAllSlides added
alkemyTech/OT207-server pull request #54
Opened 2022-06-12 21:22 UTC by softwareaim

2022-06-12 21:22 UTC, softwareaim commented
![OT207-55](https://user-images.githubusercontent.com/84826653/173254133-b0557641-7c97-4c9f-80e2-fe0a94ff15f2.jpg)

2022-06-12 21:32 UTC, softwareaim commented
nose si esta bien  usar ese dto q tambien me trae organization, ya q la tarea solo dice :
  Se debe hacer una petición GET a /Slides. 
  Devolverá el listado de Slides, con la imagen y el orden del mismo.
 Es mas otra vez lo hize igual q a la #60 xq tambien los ordene por oden. pero sino le saco el ordenamiento y hago otro dto solo con el campo imagen y orden

2022-06-13 12:34 UTC, turcoamado requested changes
Yo no traeria la organization, ya que todas las slides van a corresponder a la misma, mostraria solo la imagen (url) y el orden

2022-06-13 17:57 UTC, softwareaim commented
![OT207-55-v1 0](https://user-images.githubusercontent.com/84826653/173415317-84f4c905-5935-43c5-ac9a-b012fc230913.jpg)

2022-06-13 20:26 UTC, turcoamado approved these changes

2022-06-13 20:38 UTC, merged