OT207-80 pageable getAll public for categories
alkemyTech/OT207-server pull request #63
Opened 2022-06-14 20:08 UTC by softwareaim

![OT207-80](https://user-images.githubusercontent.com/84826653/173679352-3fba79a3-2dbf-4ec0-9396-63b7cc98ec60.jpg)

2022-06-15 04:54 UTC, turcoamado requested changes
Esta encaminado, pero en donde estas definiendo el tamanio (perdon la falta de enies y tildes) de la pagina? Tampoco estan los links a las paginas anterior y siguiente si es que existen.

2022-06-15 19:21 UTC, softwareaim commented
![OT207-80v2 0](https://user-images.githubusercontent.com/84826653/173907648-d8a0fd49-c442-4060-9ee3-901b26b52aca.jpg)

2022-06-15 19:23 UTC, softwareaim commented
![OT207-84v2 02](https://user-images.githubusercontent.com/84826653/173907921-7908c6c6-432b-4f2c-a897-b779ff7bf2e6.jpg)

2022-06-16 03:02 UTC, turcoamado approved these changes
Ahora si! Genial! Algo para que tengan en cuenta, quizas lo que codeaste para obtener los links de la pagina siguiente y anterior se puede abstraer a una clase utils para implementarlo desde alli en todos los demas lugares

2022-06-16 18:59 UTC, merged