feature/OT207-63 Agregar campos de contacto a organizations
alkemyTech/OT207-server pull request #67
Opened 2022-06-16 05:55 UTC by diego-sejas

COMO usuario administrador
QUIERO editar los campos de contacto a la Organización
PARA mostrar la información de la mejor manera posible. 

Criterios de aceptación:
Modificar modelo, repositorio y servicio para agregar las urls de redes sociales a una Organización. Se deberán agregar url de Facebook, Linkedin e Instagram

2022-06-16 06:07 UTC, diego-sejas commented
PUT con ROLE_USER
![image](https://user-images.githubusercontent.com/54463198/174001755-53d063b3-4b90-40f2-9494-114cf91854c9.png)

Con ROLE_ADMIN , petición PUT a Organización Id Inexistente
![image](https://user-images.githubusercontent.com/54463198/174002193-13cad5a2-9a14-4efb-b32d-c4ab74b96d36.png)

Con ROLE_ADMIN , petición PUT a Organización con Id 2 , actualizando datos y agregando URLs redes sociales
![image](https://user-images.githubusercontent.com/54463198/174002617-56de1304-d9f1-416d-87fc-eb480260329f.png)

BD
![image](https://user-images.githubusercontent.com/54463198/174002805-d9aea46d-c9c5-458f-8b0c-ce9e0dfa7a63.png)

2022-06-16 12:59 UTC, turcoamado requested changes
Lo que hiciste funcionalmente esta bien, el tema es que creaste todo de nuevo, habia que modificar lo existente

2022-06-16 12:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +    public ResponseEntity<OrganizationUpdateDTO> updateOrganizationById(@PathVariable("id") Long id,
Deberias haber modificado el endpoint existente, si van a utilizar este entonces el otro que es un POST no deberia estar mas, no por ser POST sino porque hacen lo mismo. Uno es obteniendo la organization directamente desde la DB asumiendo que tenemos solamente una, el otro es pasandole el id. Elijan una sola forma.
Habla con @MacaHannaArenas que fue la que hizo el anterior para ponerse de acuerdo

2022-06-16 12:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
> +    public OrganizationDTO organizationEntity2DTO(Organization entity) {
Este donde se esta usando? Esta bien que no tenga los campos nuevos? Porque quizas hay que modificar los existentes en lugar de crear dos nuevos

2022-06-16 12:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +    public OrganizationUpdateDTO updateId(Long id, OrganizationUpdateDTO organizationDTO) {
Lo mismo que antes, fijate que ya existe un metodo para hacer el update, la idea es modificar el existente y no crear uno nuevo

2022-06-17 05:32 UTC, diego-sejas commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +    public ResponseEntity<OrganizationUpdateDTO> updateOrganizationById(@PathVariable("id") Long id,
Me puse en contacto con Maca y se mantiene el endpoint existente obteniendo directamente desde la BD.

2022-06-17 05:33 UTC, diego-sejas commented on src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
> +    public OrganizationDTO organizationEntity2DTO(Organization entity) {
Eliminados.

2022-06-17 05:34 UTC, diego-sejas commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +    public OrganizationUpdateDTO updateId(Long id, OrganizationUpdateDTO organizationDTO) {
Si , si pasa que no quería tocar lo que ya estaba.

2022-06-17 05:39 UTC, diego-sejas commented
Utilizando el endpoint existente organization/public , pasándole el id de la organización y los campos a actualizar o agregar las URLs de redes sociales de contacto , se actualiza .
![image](https://user-images.githubusercontent.com/54463198/174232445-ad6d023a-ae29-4bb2-a159-ff9650bfe56e.png)

![image](https://user-images.githubusercontent.com/54463198/174232542-fdb8ae3d-45a6-430a-9664-6e717c977d9e.png)

2022-06-17 17:14 UTC, turcoamado approved these changes

2022-06-17 19:46 UTC, merged