feature/OT207-77 Endpoint Actualización Comentarios
alkemyTech/OT207-server pull request #69
Opened 2022-06-18 04:32 UTC by diego-sejas

COMO usuario
QUIERO actualizar un comentario propio
PARA mantener la información actualizada

Criterios de aceptación:
PUT /comments/:id - Deberá validar la existencia del comentario en base a su id. Solamente podrán editar un comentario el usuario que lo realizó o un administrador. Deberá devolver un código de error 404 si el comentario no existe, o 403 si no tiene permiso para modificarlo.

2022-06-18 04:58 UTC, diego-sejas commented
Tabla Commentaries.
![image](https://user-images.githubusercontent.com/54463198/174422957-a621bef0-0453-4cb3-adc0-d0fcbf889673.png)

PUT a http://localhost:8080/comments/30 - id inexistente
![image](https://user-images.githubusercontent.com/54463198/174422990-b61f0585-896c-4f12-8b73-a148cf2b2093.png)

Tabla Users.
![image](https://user-images.githubusercontent.com/54463198/174423046-3e9eb135-a0f0-422c-94e6-e179b47f50f0.png)

Tratando de modificar comentario id 3 , creador por user_id : 27 con usuario user_id : 29  ambos ROLE_USER
![image](https://user-images.githubusercontent.com/54463198/174423231-40972105-b20e-4324-a718-ddc6e97ce4fa.png)

Modificando comentario id 3 , por el mismo usuario que lo creo user:id : 27 , ROLE_USER
![image](https://user-images.githubusercontent.com/54463198/174423303-feea75a9-7d3c-40a7-93e8-a84337fb1d44.png)

Tabla
![image](https://user-images.githubusercontent.com/54463198/174423321-eb3ad12d-968f-428d-9d59-8a31e5ecc5c9.png)

Modificando con cualquier user ROLE_ADMIN , en este caso con el user_id : 28 , un comentario que fue creado por otro ADMIN user_id : 26
![image](https://user-images.githubusercontent.com/54463198/174423434-68a1102f-e7c1-4620-90ab-fb70438b70f0.png)

Tabla
![image](https://user-images.githubusercontent.com/54463198/174423460-b932bcfc-8a91-4c6b-b58b-1ea04677163e.png)

2022-06-20 06:14 UTC, turcoamado requested changes
Esta muy bueno! Te marque solo una pavada en el controller con respecto al status http

2022-06-20 06:14 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CommentaryController.java
> +        return new ResponseEntity<>(commentaryService.update(id, dto ,request), HttpStatus.CREATED);
Aca utilizaria un HttpStatus.OK en lugar de CREATED, ya que no estas creando nada sino haciendo un update

2022-06-20 15:15 UTC, diego-sejas commented on src/main/java/com/alkemy/ong/controller/CommentaryController.java
> +        return new ResponseEntity<>(commentaryService.update(id, dto ,request), HttpStatus.CREATED);
Ok, buenísimo turco , dale ahí lo modifico para la próxima tarea en PR ya estará incluido.

2022-06-20 15:15 UTC, merged