OT207-91 testing controller members
alkemyTech/OT207-server pull request #73
Opened 2022-06-22 03:21 UTC by softwareaim

2022-06-22 03:21 UTC, softwareaim commented
![OT207-91-Test](https://user-images.githubusercontent.com/84826653/174936532-b7b6c55a-898c-48ca-8eff-35b47b155d25.jpg)

2022-06-22 03:22 UTC, softwareaim commented
![OT207-91-test2](https://user-images.githubusercontent.com/84826653/174936571-bfdfd896-06ee-4d15-b168-22e695bc8c06.jpg)

2022-06-23 03:55 UTC, turcoamado requested changes
Bueno lo que hiciste esta realmente muy bien, hasta create la DB para correr los test de forma independiente del resto del codigo.
Con que hubieses realizado la segunda clase que aparece (la que no tiene IT) estaba bien, sin necesidad de crear la base de datos, pero esta buenisimo lo que hiciste.

Te marque dos pavadas, una es la de las variables privadas, la otra que aproveches la annotation @BeforeEach que veo que usas en una de las clases, la construccion del DTO la podes meter bajo esa annotation tambien para evitar repetir el codigo en todos los test.

Ah y setearle el orden de ejecucion no se si seria totalmente necesario en este caso, y digo no se porque quizas vos ya te diste cuenta de que si necesitas uno si o si antes que otro.

2022-06-23 03:55 UTC, turcoamado commented on src/test/java/com/alkemy/ong/controller/MemberControllerIT.java
> +        MemberDTO request = MemberDTO.builder()
Este objeto que creas lo podes hacer fuera de todos los test y bajo la annotation @BeforeEach, lo que haces con eso es indicarle que se va a ejecutar antes de los test. Para no repetir siempre lo mismo en todos los casos

2022-06-23 03:55 UTC, turcoamado commented on src/test/java/com/alkemy/ong/controller/MemberControllerIT.java
> +    MockMvc mockMvc;
Las variables hacelas de tipo private

2022-06-23 03:55 UTC, turcoamado commented on src/test/java/com/alkemy/ong/controller/MemberControllerTest.java
> +    MemberController controller;
Las variables hacelas de tipo private

2022-06-23 03:55 UTC, turcoamado commented on src/test/java/com/alkemy/ong/controller/MemberControllerTest.java
> +        MemberDTO request = MemberDTO.builder()
Lo mismo que te mencione arriba, y veo que ya hiciste uso de la annotation

2022-06-23 13:45 UTC, softwareaim commented
Gracias turco la verdad se me re pasaron esos detalles.

2022-06-23 22:17 UTC, turcoamado approved these changes
Esta barbaro!

2022-06-24 00:47 UTC, merged