Agregar paginación a Miembros
alkemyTech/OT207-server pull request #78
Opened 2022-06-25 23:56 UTC by MacaHannaArenas

![imagen](https://user-images.githubusercontent.com/92378693/175794017-c5e174d4-a3f4-4247-9e5a-cb302be2f33d.png)

2022-06-26 20:58 UTC, turcoamado requested changes
Fijate eso que te mencione para reutilizar la clase Url dentro de utils. Lo otro esta bien

2022-06-26 20:58 UTC, turcoamado commented on src/main/java/com/alkemy/ong/domain/service/impl/MemberServiceImpl.java
> +        if (member.isEmpty()) {
Maca estos if creo que estaban en un Util. Fijate la clase Url.java que esta ahi dentro, podes llamar a eso en lugar de codearlos aca. En la clase _NewsServiceImpl_ hay un ejemplo

2022-06-26 22:22 UTC, MacaHannaArenas commented on src/main/java/com/alkemy/ong/domain/service/impl/MemberServiceImpl.java
> +        if (member.isEmpty()) {
gracias!

2022-06-26 22:32 UTC, MacaHannaArenas commented on src/main/java/com/alkemy/ong/domain/service/impl/MemberServiceImpl.java
> +        if (member.isEmpty()) {
Ahi lo arregle

2022-06-27 15:09 UTC, turcoamado approved these changes

2022-06-27 15:48 UTC, MacaHannaArenas commented
![imagen](https://user-images.githubusercontent.com/92378693/175980855-cb635d8f-0c17-4847-9a8e-7626639f0853.png)
![imagen](https://user-images.githubusercontent.com/92378693/175980908-27c4348e-41dc-4af7-8b1c-f1e198cce1b5.png)

2022-06-27 15:48 UTC, merged